// <auto-generated />
namespace TheFlow.Api.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SwitchedPostsToUseEdits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SwitchedPostsToUseEdits));
        
        string IMigrationMetadata.Id
        {
            get { return "201308300402433_SwitchedPostsToUseEdits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
