// <auto-generated />
namespace TheFlow.Api.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedValueToVotes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedValueToVotes));
        
        string IMigrationMetadata.Id
        {
            get { return "201309210059310_AddedValueToVotes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
