// <auto-generated />
namespace TheFlow.API.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EditBodyColumnTypeToNText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditBodyColumnTypeToNText));
        
        string IMigrationMetadata.Id
        {
            get { return "201308130352046_EditBodyColumnTypeToNText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
